"""Render a discovered circuit to Markdown + a standalone SVG diagram."""

from __future__ import annotations

from typing import Dict, List

from verigrad_rl.mech.acdc import ACDCResult
from verigrad_rl.mech.circuit_graph import CircuitGraph

INK = "#0b1f33"
TEAL = "#0f766e"
BLUE = "#0369a1"
AMBER = "#b45309"
MUTED = "#8694a1"
LINE = "#d7dee6"


def render_markdown(graph: CircuitGraph, result: ACDCResult, *, title: str) -> str:
    kept = sorted(result.circuit_edges)
    lines = [
        f"# {title}",
        "",
        "Automated circuit discovery (ACDC; Conmy et al., NeurIPS 2023) over a transparent",
        "safety circuit, using path patching (Goldowsky-Dill et al., 2023) as the causal",
        "primitive. Generated by `verigrad circuit` — do not edit by hand.",
        "",
        f"- **Edges kept:** {result.n_edges} of {result.full_edges} "
        f"(sparsity {result.sparsity:.0%})",
        f"- **Faithfulness:** KL(clean ‖ circuit-only) = {result.faithfulness_kl:.4f} nats "
        f"(lower = the circuit reproduces the behavior)",
        f"- **Threshold:** tau = {result.tau} nats per edge",
        "",
        "## Discovered circuit (kept edges)",
        "",
        "| parent | → | child |",
        "|---|---|---|",
    ]
    lines += [f"| `{u}` | → | `{v}` |" for (u, v) in kept]
    lines += ["", "## Pruned edges", ""]
    lines += [f"- `{u}` → `{v}`" for (u, v) in result.pruned_edges] or ["- (none)"]
    lines.append("")
    return "\n".join(lines)


def render_svg(graph: CircuitGraph, result: ACDCResult, *, title: str) -> str:
    layers: Dict[int, List[str]] = {}
    for name, node in graph.nodes.items():
        layers.setdefault(node.layer, []).append(name)
    for names in layers.values():
        names.sort()

    W, H = 760, 380
    pad_x, pad_top = 70, 70
    n_layers = max(layers) + 1
    gap_x = (W - 2 * pad_x) / max(n_layers - 1, 1)
    pos: Dict[str, tuple[float, float]] = {}
    for layer, names in sorted(layers.items()):
        x = pad_x + layer * gap_x
        span = H - pad_top - 40
        step = span / max(len(names), 1)
        for i, name in enumerate(names):
            y = pad_top + step * (i + 0.5)
            pos[name] = (x, y)

    kept = set(result.circuit_edges)
    parts: List[str] = [
        f'<svg viewBox="0 0 {W} {H}" xmlns="http://www.w3.org/2000/svg" '
        f'font-family="Inter, ui-sans-serif, system-ui, sans-serif">',
        f'<rect width="{W}" height="{H}" fill="#ffffff"/>',
        f'<text x="{W/2}" y="30" text-anchor="middle" font-size="17" font-weight="800" '
        f'fill="{INK}">{title}</text>',
        f'<text x="{W/2}" y="50" text-anchor="middle" font-size="12" fill="{MUTED}">'
        f'ACDC over a transparent safety circuit · {result.n_edges}/{result.full_edges} edges kept · '
        f'faithfulness KL {result.faithfulness_kl:.3f} · tau {result.tau}</text>',
    ]

    # edges
    for (u, v) in graph.edges():
        x1, y1 = pos[u]
        x2, y2 = pos[v]
        if (u, v) in kept:
            parts.append(
                f'<line x1="{x1:.0f}" y1="{y1:.0f}" x2="{x2:.0f}" y2="{y2:.0f}" '
                f'stroke="{TEAL}" stroke-width="2.2" opacity="0.85"/>'
            )
        else:
            parts.append(
                f'<line x1="{x1:.0f}" y1="{y1:.0f}" x2="{x2:.0f}" y2="{y2:.0f}" '
                f'stroke="{LINE}" stroke-width="1.2" stroke-dasharray="4 4"/>'
            )

    # nodes
    for name, (x, y) in pos.items():
        node = graph.nodes[name]
        if node.is_input:
            fill, stroke = "#eef2f6", MUTED
        elif name in graph.outputs:
            fill, stroke = "#fff7ed", AMBER
        else:
            fill, stroke = "#eff6ff", BLUE
        rw = max(54, 8 * len(name) + 16)
        parts.append(
            f'<rect x="{x-rw/2:.0f}" y="{y-13:.0f}" width="{rw}" height="26" rx="8" '
            f'fill="{fill}" stroke="{stroke}" stroke-width="1.4"/>'
        )
        parts.append(
            f'<text x="{x:.0f}" y="{y+4:.0f}" text-anchor="middle" font-size="11.5" '
            f'font-weight="650" fill="{INK}">{name}</text>'
        )

    # legend
    parts.append(
        f'<line x1="{pad_x}" y1="{H-18}" x2="{pad_x+26}" y2="{H-18}" stroke="{TEAL}" stroke-width="2.2"/>'
        f'<text x="{pad_x+32}" y="{H-14}" font-size="11" fill="{MUTED}">kept (in circuit)</text>'
        f'<line x1="{pad_x+150}" y1="{H-18}" x2="{pad_x+176}" y2="{H-18}" stroke="{LINE}" '
        f'stroke-width="1.2" stroke-dasharray="4 4"/>'
        f'<text x="{pad_x+182}" y="{H-14}" font-size="11" fill="{MUTED}">pruned</text>'
    )
    parts.append("</svg>")
    return "\n".join(parts)
